baseURL = 'https://jonnydford.github.io/'
languageCode = 'en-us'
title = 'jonnydford'

theme = "m10c"
author = 'Jonny Ford'

[[params]]
author = 'Jonny Ford'
avatar = ""
description = 'Senior Engineering Manager of Data Platforms at Just Eat Takeaway.com'

[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/jonnydford"
